### PR TITLE
Tokenising

### PR DESCRIPTION
**Pull request by aniasobo**
Tokeniser now has:  
* a TOKENS constant
* a create_tokens() method that returns an array of dictionaries

Problems:  
* only the first match is returned by create_tokens(); needs a refactor to remove the match from the searched string(self.text) and continue to loop

### CODE REVIEW

**Review by zepherine2006DEV — APPROVED** [review]
Yay!

**Review by josephtownshend — COMMENTED** [review]
nice

**Review by lucianmot — APPROVED** [review]
:snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail:

**Review by ajmpawlik — APPROVED** [review]
wow!

**Pull request merged**
